hash-format = "sha256"

[[files]]
file = "LICENCE.txt"
hash = "3972dc9744f6499f0f9b2dbf76696f2ae7ad8af9b23dde66d6af86c9dfb36986"

[[files]]
file = "README.md"
hash = "95ce04de64e5a7fb9a3b5db94cca0446e385dde489e3500d3761a402567e98ab"

[[files]]
file = "flake.lock"
hash = "ec544b806990af357a3888fef014c79c708ea104c63f0b3b277c25bde1757e1c"

[[files]]
file = "flake.nix"
hash = "1b5c2140b2ad331ee832d0e3da785454c9de1f98da98eae486dc04f5d4a7c7af"

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "4e81241ba2da06f425efc5e09fb6b38470125c1581c39e1310c5843a0b96ec76"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "97f7c75ac9bf6ee2a4f15c0f1e3e4cd161f3d2e33f32ebf623811ac90b3c2a83"
metafile = true

[[files]]
file = "mods/destroy.pw.toml"
hash = "3ec1b526c89e0cc060827954e50c14dfd8411380f73f733ab160c049fadc3470"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "70a4ecd9d0c04ad20aeb976c1ee28933ce48a0a1f43df42deafaeb2ad7235297"
metafile = true

[[files]]
file = "mods/petrolpark.pw.toml"
hash = "9e0e6977137d55d1d4f32188e351a59836d661cfd0317522da36d3005f01f3a9"
metafile = true

[[files]]
file = "mods/power-grid.pw.toml"
hash = "15deca95981302f47ebc81d38195b91c88512b84ded1ea909a8c24a758a63a64"
metafile = true

[[files]]
file = "mods/trackwork.pw.toml"
hash = "3f2cada5f40ad16426b177a8d5cc1b715e031ece0754f3c64c08efbf0217e020"
metafile = true

[[files]]
file = "mods/valkyrien-skies.pw.toml"
hash = "752beea8634d215652b339eef69d592a647462b80654feaaf44b79fc4cbb4f6d"
metafile = true
