name = "Minecraft Industiral Complex"
author = "benmac"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7650c69819b8e7c99fee1fddb3a63ae538f9cc07128ddd80fbf28625fae7b177"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
