name = "Minecraft Industiral Complex"
author = "benmac"
version = "1.0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04a633f0e8d642da26f9880f8ac1e8f5f2c02ee20cd4669fefcc9007a450b4c0"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
