name = "Minecraft Industiral Complex"
author = "benmac"
version = "1.0.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a53722d411a85f8e9bdb56d9e4aa1d78468f0c687bc0755ebdbfd3944d27038b"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
