name = "Minecraft Industiral Complex"
author = "benmac"
version = "1.0.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ec62d6db1bfe7292805a359dd70999611f149921ac12e35f914af6d8721b17b"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
