name = "Minecraft Industiral Complex"
author = "benmac"
version = "1.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2934e46dca749740939fa34c186af49a0a7818d47425d7acbf59f30d99b2e5a0"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
