name = "Minecraft Industiral Complex"
author = "benmac"
version = "1.0.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc05dc0733487022560cc8bdf5ac3d022e9d5a61b56c9a3b3096f4990794e769"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
