name = "Minecraft Industiral Complex"
author = "benmac"
version = "1.0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd9917f351f80dc5e83ed0dcc049a2252adef4378eb89770ca29e8228ab1cf9e"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
