name = "Minecraft Industiral Complex"
author = "benmac"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "288b3f817b0c5be997774e075aa5c0b90331019acf1410650ccd39594e633094"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
