name = "Minecraft Industiral Complex"
author = "benmac"
version = "1.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5e6e7bbbb16d29d28aaf8581bdde8943d2ce6b16facbdf70508ed4ae694f668"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
