name = "Minecraft Industiral Complex"
author = "benmac"
version = "1.0.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e3db8f1cc1be75f700fceb96a1b59717124138f7b744fcdf8fd1ef7876ffe40"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
