name = "Minecraft Industiral Complex"
author = "benmac"
version = "1.0.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a38b6079bbf69e254994f9b573a41abdbe7a65c2e63005722478dbe09b094089"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
