name = "Minecraft Industiral Complex"
author = "benmac"
version = "1.0.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6db21f662e0a97124913b6becf1719201c6f4b70f0383506f791b78d4acab6c9"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
