name = "Minecraft Industiral Complex"
author = "benmac"
version = "1.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8af24d178107b68b353ab8f97cc9ebc9b2aab4605069040db96c9412f69a203"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
