name = "Minecraft Industiral Complex"
author = "benmac"
version = "1.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8c38c730cfa402145d22b417347f38d8db35249fc20f33b3b6cb24567414a7a"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
