name = "Minecraft Industiral Complex"
author = "benmac"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e83fb0352b7af574a9e9c09a780f1992e3b0784b25c806c80d04c76f337e50b1"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
