name = "Minecraft Industiral Complex"
author = "benmac"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb05be80ce8250d0617282faad1cf067ac389b8f9226a3e97d1f6dd1e7b89f90"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
