name = "Minecraft Industiral Complex"
author = "benmac"
version = "1.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b16ae1e2e6dd92378bc829d054e486d73f67d5c68fde63fff88131e3a6b9bbd1"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
