name = "Minecraft Industiral Complex"
author = "benmac"
version = "1.0.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8499750d21915899d2eeb642b74d7e1185c93a91af3099fca501bef92724b66"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
