name = "Minecraft Industiral Complex"
author = "benmac"
version = "1.0.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1dc305165e542afa3ccc4190787b80b3dfc334634a531a5457b6cc2a00e3f6a8"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
