name = "Minecraft Industiral Complex"
author = "benmac"
version = "1.0.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bec6d450c21aa99361bd195336148ff16fab5f55ef3def023c1d153d4e690d3d"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
