name = "Minecraft Industiral Complex"
author = "benmac"
version = "1.0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32b3717a0b89e4efccdd1ccc5df2ab14917cbc208d47ef03af8584adccaf8a97"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
